name: flutter_dittofeed
description: "A Dart implementation of the Dittofeed SDK for Flutter applications."
homepage: https://github.com/fadilhim/flutter_dittofeed
repository: https://github.com/fadilhim/flutter_dittofeed
version: 0.0.3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.5
  test: ^1.25.15

